# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_CLINTERCEPT_FILE_NAME "clintercept-3.0.6-")
set(CPACK_ARCHIVE_COMPONENT_INSTALL "ON")
set(CPACK_ARCHIVE_GID "-1")
set(CPACK_ARCHIVE_UID "-1")
set(CPACK_BUILD_SOURCE_DIRS "/data/data/com.termux/files/home/tmp_turboquant/third_party/OpenCL-Intercept-Layer;/data/data/com.termux/files/home/tmp_turboquant/.cache/opencl-intercept-build")
set(CPACK_CMAKE_GENERATOR "Ninja")
set(CPACK_COMPONENT_INSTALL "ON")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_CLINTERCEPT_FILE_NAME "clintercept_3.0.6_.deb")
set(CPACK_DEBIAN_COMPRESSION_TYPE "xz")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Intel")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS "ON")
set(CPACK_DEB_COMPONENT_INSTALL "ON")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/data/data/com.termux/files/usr/share/cmake-4.3/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "CLIntercept built using CMake")
set(CPACK_GENERATOR "TGZ")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "/data/data/com.termux/files/home/tmp_turboquant/.cache/opencl-intercept-build;CLIntercept;ALL;/")
set(CPACK_INSTALL_PREFIX "/data/data/com.termux/files/home/tmp_turboquant/.cache/opencl-intercept-install")
set(CPACK_MODULE_PATH "")
set(CPACK_NSIS_DISPLAY_NAME "clintercept 3.0.6")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "clintercept 3.0.6")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/data/data/com.termux/files/usr/bin/llvm-objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/data/data/com.termux/files/usr/bin/llvm-objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/data/data/com.termux/files/home/tmp_turboquant/.cache/opencl-intercept-build/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/data/data/com.termux/files/usr/share/cmake-4.3/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Intercept Layer for OpenCL(tm) Applications")
set(CPACK_PACKAGE_FILE_NAME "clintercept-3.0.6-Android")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/intel/opencl-intercept-layer/")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "clintercept 3.0.6")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "clintercept 3.0.6")
set(CPACK_PACKAGE_NAME "clintercept")
set(CPACK_PACKAGE_RELOCATABLE "false")
set(CPACK_PACKAGE_VENDOR "Intel(R) Corporation")
set(CPACK_PACKAGE_VERSION "3.0.6")
set(CPACK_PACKAGE_VERSION_MAJOR "3")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "6")
set(CPACK_READELF_EXECUTABLE "/data/data/com.termux/files/usr/bin/llvm-readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/data/data/com.termux/files/usr/share/cmake-4.3/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/data/data/com.termux/files/usr/share/cmake-4.3/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/data/data/com.termux/files/usr/share/cmake-4.3/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_CLINTERCEPT_FILE_NAME "clintercept-3.0.6-1%{?dist}..rpm")
set(CPACK_RPM_COMPONENT_INSTALL "ON")
set(CPACK_RPM_COMPRESSION_TYPE "xz")
set(CPACK_RPM_PACKAGE_RELEASE "1")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_IGNORE_FILES "/\\.git/;/\\.vscode/;build*/;_bin*/;_test*/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/data/data/com.termux/files/home/tmp_turboquant/.cache/opencl-intercept-build/CPackSourceConfig.cmake")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_SYSTEM_NAME "Android")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Android")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/data/data/com.termux/files/home/tmp_turboquant/.cache/opencl-intercept-build/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
